//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaloniaToDoListTrackerAndVisualizer.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AvaloniaToDoListTrackerAndVisualizer.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string HomeButton {
            get {
                return ResourceManager.GetString("HomeButton", resourceCulture);
            }
        }
        
        public static string TreeButton {
            get {
                return ResourceManager.GetString("TreeButton", resourceCulture);
            }
        }
        
        public static string ProfileButton {
            get {
                return ResourceManager.GetString("ProfileButton", resourceCulture);
            }
        }
        
        public static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        public static string AddTaskButton {
            get {
                return ResourceManager.GetString("AddTaskButton", resourceCulture);
            }
        }
        
        public static string AddEventButton {
            get {
                return ResourceManager.GetString("AddEventButton", resourceCulture);
            }
        }
        
        public static string StartSessionButton {
            get {
                return ResourceManager.GetString("StartSessionButton", resourceCulture);
            }
        }
        
        public static string CompleteButton {
            get {
                return ResourceManager.GetString("CompleteButton", resourceCulture);
            }
        }
        
        public static string UnCompleteButton {
            get {
                return ResourceManager.GetString("UnCompleteButton", resourceCulture);
            }
        }
        
        public static string DetailsButton {
            get {
                return ResourceManager.GetString("DetailsButton", resourceCulture);
            }
        }
        
        public static string ReadyButton {
            get {
                return ResourceManager.GetString("ReadyButton", resourceCulture);
            }
        }
        
        public static string DoneButton {
            get {
                return ResourceManager.GetString("DoneButton", resourceCulture);
            }
        }
        
        public static string AllButton {
            get {
                return ResourceManager.GetString("AllButton", resourceCulture);
            }
        }
        
        public static string EditTaskWindowName {
            get {
                return ResourceManager.GetString("EditTaskWindowName", resourceCulture);
            }
        }
        
        public static string GoBackButton {
            get {
                return ResourceManager.GetString("GoBackButton", resourceCulture);
            }
        }
        
        public static string TaskDefaultName {
            get {
                return ResourceManager.GetString("TaskDefaultName", resourceCulture);
            }
        }
        
        public static string SaveAndBackButton {
            get {
                return ResourceManager.GetString("SaveAndBackButton", resourceCulture);
            }
        }
        
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        public static string DeleteSwitchOff {
            get {
                return ResourceManager.GetString("DeleteSwitchOff", resourceCulture);
            }
        }
        
        public static string DeleteSwitchOn {
            get {
                return ResourceManager.GetString("DeleteSwitchOn", resourceCulture);
            }
        }
        
        public static string BeginDateText {
            get {
                return ResourceManager.GetString("BeginDateText", resourceCulture);
            }
        }
        
        public static string SoftDeadlineText {
            get {
                return ResourceManager.GetString("SoftDeadlineText", resourceCulture);
            }
        }
        
        public static string HardDeadlineText {
            get {
                return ResourceManager.GetString("HardDeadlineText", resourceCulture);
            }
        }
        
        public static string NoDeadlineSet {
            get {
                return ResourceManager.GetString("NoDeadlineSet", resourceCulture);
            }
        }
        
        public static string DaysUntilSoftDeadline {
            get {
                return ResourceManager.GetString("DaysUntilSoftDeadline", resourceCulture);
            }
        }
        
        public static string DaysUntilHardDeadline {
            get {
                return ResourceManager.GetString("DaysUntilHardDeadline", resourceCulture);
            }
        }
        
        public static string DaysUntilBeginDate {
            get {
                return ResourceManager.GetString("DaysUntilBeginDate", resourceCulture);
            }
        }
        
        public static string DaysAfterBeginNoDeadline {
            get {
                return ResourceManager.GetString("DaysAfterBeginNoDeadline", resourceCulture);
            }
        }
        
        public static string DaysAfterSoft {
            get {
                return ResourceManager.GetString("DaysAfterSoft", resourceCulture);
            }
        }
        
        public static string DaysAfterHard {
            get {
                return ResourceManager.GetString("DaysAfterHard", resourceCulture);
            }
        }
        
        public static string TimeSpentText {
            get {
                return ResourceManager.GetString("TimeSpentText", resourceCulture);
            }
        }
        
        public static string HoursText {
            get {
                return ResourceManager.GetString("HoursText", resourceCulture);
            }
        }
        
        public static string MinutesText {
            get {
                return ResourceManager.GetString("MinutesText", resourceCulture);
            }
        }
        
        public static string TimeExpectedText {
            get {
                return ResourceManager.GetString("TimeExpectedText", resourceCulture);
            }
        }
        
        public static string NotSetText {
            get {
                return ResourceManager.GetString("NotSetText", resourceCulture);
            }
        }
        
        public static string SubTaskEditWindowName {
            get {
                return ResourceManager.GetString("SubTaskEditWindowName", resourceCulture);
            }
        }
        
        public static string AddSubTaskButton {
            get {
                return ResourceManager.GetString("AddSubTaskButton", resourceCulture);
            }
        }
        
        public static string NewSubTaskName {
            get {
                return ResourceManager.GetString("NewSubTaskName", resourceCulture);
            }
        }
        
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        public static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        public static string SelectGroupText {
            get {
                return ResourceManager.GetString("SelectGroupText", resourceCulture);
            }
        }
        
        public static string GroupSelectionWindowName {
            get {
                return ResourceManager.GetString("GroupSelectionWindowName", resourceCulture);
            }
        }
        
        public static string SelectText {
            get {
                return ResourceManager.GetString("SelectText", resourceCulture);
            }
        }
        
        public static string NewGroupButton {
            get {
                return ResourceManager.GetString("NewGroupButton", resourceCulture);
            }
        }
        
        public static string AssignNoGroupButton {
            get {
                return ResourceManager.GetString("AssignNoGroupButton", resourceCulture);
            }
        }
        
        public static string GroupNameWatermark {
            get {
                return ResourceManager.GetString("GroupNameWatermark", resourceCulture);
            }
        }
        
        public static string NewGroupPlaceholderName {
            get {
                return ResourceManager.GetString("NewGroupPlaceholderName", resourceCulture);
            }
        }
        
        public static string ManagePrerequisitesText {
            get {
                return ResourceManager.GetString("ManagePrerequisitesText", resourceCulture);
            }
        }
        
        public static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        public static string PrerequisiteSelectionDialog {
            get {
                return ResourceManager.GetString("PrerequisiteSelectionDialog", resourceCulture);
            }
        }
        
        public static string SelectTasksText {
            get {
                return ResourceManager.GetString("SelectTasksText", resourceCulture);
            }
        }
        
        public static string SelectedTasksText {
            get {
                return ResourceManager.GetString("SelectedTasksText", resourceCulture);
            }
        }
        
        public static string ToggleSelectionButton {
            get {
                return ResourceManager.GetString("ToggleSelectionButton", resourceCulture);
            }
        }
        
        public static string SessionWindow {
            get {
                return ResourceManager.GetString("SessionWindow", resourceCulture);
            }
        }
        
        public static string SessionTotalText {
            get {
                return ResourceManager.GetString("SessionTotalText", resourceCulture);
            }
        }
        
        public static string SelectTaskText {
            get {
                return ResourceManager.GetString("SelectTaskText", resourceCulture);
            }
        }
        
        public static string SessionTaskSelectionDialog {
            get {
                return ResourceManager.GetString("SessionTaskSelectionDialog", resourceCulture);
            }
        }
        
        public static string SelectTaskToWorkOnText {
            get {
                return ResourceManager.GetString("SelectTaskToWorkOnText", resourceCulture);
            }
        }
        
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        public static string TaskText {
            get {
                return ResourceManager.GetString("TaskText", resourceCulture);
            }
        }
        
        public static string SubtaskText {
            get {
                return ResourceManager.GetString("SubtaskText", resourceCulture);
            }
        }
        
        public static string TimerSelectionDialog {
            get {
                return ResourceManager.GetString("TimerSelectionDialog", resourceCulture);
            }
        }
        
        public static string RegularTimerText {
            get {
                return ResourceManager.GetString("RegularTimerText", resourceCulture);
            }
        }
        
        public static string PomodoroTimerText {
            get {
                return ResourceManager.GetString("PomodoroTimerText", resourceCulture);
            }
        }
        
        public static string WorkTimeText {
            get {
                return ResourceManager.GetString("WorkTimeText", resourceCulture);
            }
        }
        
        public static string ShortBreakTimeText {
            get {
                return ResourceManager.GetString("ShortBreakTimeText", resourceCulture);
            }
        }
        
        public static string LongBreakTimeText {
            get {
                return ResourceManager.GetString("LongBreakTimeText", resourceCulture);
            }
        }
        
        public static string ShortBreaksBeforeLongText {
            get {
                return ResourceManager.GetString("ShortBreaksBeforeLongText", resourceCulture);
            }
        }
        
        public static string ComingSoonText {
            get {
                return ResourceManager.GetString("ComingSoonText", resourceCulture);
            }
        }
        
        public static string TestNotificationSoundText {
            get {
                return ResourceManager.GetString("TestNotificationSoundText", resourceCulture);
            }
        }
        
        public static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        public static string SkipWorkText {
            get {
                return ResourceManager.GetString("SkipWorkText", resourceCulture);
            }
        }
        
        public static string SkipBreakText {
            get {
                return ResourceManager.GetString("SkipBreakText", resourceCulture);
            }
        }
        
        public static string EndText {
            get {
                return ResourceManager.GetString("EndText", resourceCulture);
            }
        }
        
        public static string WorkLeftText {
            get {
                return ResourceManager.GetString("WorkLeftText", resourceCulture);
            }
        }
        
        public static string OvertimeText {
            get {
                return ResourceManager.GetString("OvertimeText", resourceCulture);
            }
        }
        
        public static string BreakLeftText {
            get {
                return ResourceManager.GetString("BreakLeftText", resourceCulture);
            }
        }
        
        public static string OverBreakText {
            get {
                return ResourceManager.GetString("OverBreakText", resourceCulture);
            }
        }
        
        public static string NoGroupText {
            get {
                return ResourceManager.GetString("NoGroupText", resourceCulture);
            }
        }
        
        public static string TotalTimeText {
            get {
                return ResourceManager.GetString("TotalTimeText", resourceCulture);
            }
        }
        
        public static string MostProductiveDayText {
            get {
                return ResourceManager.GetString("MostProductiveDayText", resourceCulture);
            }
        }
        
        public static string WorkedTodayText {
            get {
                return ResourceManager.GetString("WorkedTodayText", resourceCulture);
            }
        }
        
        public static string AveragePerDay {
            get {
                return ResourceManager.GetString("AveragePerDay", resourceCulture);
            }
        }
        
        public static string GoalText {
            get {
                return ResourceManager.GetString("GoalText", resourceCulture);
            }
        }
        
        public static string GoalNotYetAchievedText {
            get {
                return ResourceManager.GetString("GoalNotYetAchievedText", resourceCulture);
            }
        }
        
        public static string DeleteSessionsDataText {
            get {
                return ResourceManager.GetString("DeleteSessionsDataText", resourceCulture);
            }
        }
        
        public static string RefreshButtonText {
            get {
                return ResourceManager.GetString("RefreshButtonText", resourceCulture);
            }
        }
        
        public static string SessionDeletionDialog {
            get {
                return ResourceManager.GetString("SessionDeletionDialog", resourceCulture);
            }
        }
        
        public static string SessionDeletionVerification {
            get {
                return ResourceManager.GetString("SessionDeletionVerification", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string GoalAchievedText {
            get {
                return ResourceManager.GetString("GoalAchievedText", resourceCulture);
            }
        }
    }
}
