//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaloniaToDoListTrackerAndVisualizer.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AvaloniaToDoListTrackerAndVisualizer.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string HomeButton {
            get {
                return ResourceManager.GetString("HomeButton", resourceCulture);
            }
        }
        
        public static string TreeButton {
            get {
                return ResourceManager.GetString("TreeButton", resourceCulture);
            }
        }
        
        public static string ProfileButton {
            get {
                return ResourceManager.GetString("ProfileButton", resourceCulture);
            }
        }
        
        public static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        public static string AddTaskButton {
            get {
                return ResourceManager.GetString("AddTaskButton", resourceCulture);
            }
        }
        
        public static string AddEventButton {
            get {
                return ResourceManager.GetString("AddEventButton", resourceCulture);
            }
        }
        
        public static string StartSessionButton {
            get {
                return ResourceManager.GetString("StartSessionButton", resourceCulture);
            }
        }
        
        public static string CompleteButton {
            get {
                return ResourceManager.GetString("CompleteButton", resourceCulture);
            }
        }
        
        public static string UnCompleteButton {
            get {
                return ResourceManager.GetString("UnCompleteButton", resourceCulture);
            }
        }
        
        public static string DetailsButton {
            get {
                return ResourceManager.GetString("DetailsButton", resourceCulture);
            }
        }
        
        public static string ReadyButton {
            get {
                return ResourceManager.GetString("ReadyButton", resourceCulture);
            }
        }
        
        public static string DoneButton {
            get {
                return ResourceManager.GetString("DoneButton", resourceCulture);
            }
        }
        
        public static string AllButton {
            get {
                return ResourceManager.GetString("AllButton", resourceCulture);
            }
        }
    }
}
